# Questionário 6 e 7

Nomes:
    
SME0824 - Gestão da Qualidade

## Importação dos pacotes

In [1]:
# !pip install GaugeRnR

In [2]:
# Importação das bibliotecas
import pandas as pd
import csv
import numpy as np
import GaugeRnR
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sns
plt.style.use('seaborn-colorblind')

## Funções útei para o projeto

In [3]:
def amplitude(valor):
    minimo = min(valor)
    maximo = max(valor)
    return maximo - minimo

## Criando o dataset

Para a criação desse dataset, consideramos que estamos na cidade de São Carlos e desejamos estudar o tempo de entrega dos pedidos (em minutos) de um certo restaurante em um raio de até 2km. Além disso, todos os dados utilizados são fictícios.

Supomos que os dados possuem uma  distribuição normal com uma certa média, um certo desvio-padrão e com 30 amostras de tamanho 5:

In [4]:
# Fixamos uma semente para reproduzir o estudo e obter os mesmos resultados
np.random.seed(0)
mu, sigma = 30, 5 # Média e desvio padrão (em minutos)
s = np.random.normal(mu, sigma, 150)

s = np. reshape(s, (30, 5))
s =pd.DataFrame(s)
s

            0          1          2          3          4
0   38.820262  32.000786  34.893690  41.204466  39.337790
1   25.113611  34.750442  29.243214  29.483906  32.052993
2   30.720218  37.271368  33.805189  30.608375  32.219316
3   31.668372  37.470395  28.974209  31.565339  25.729521
4   17.235051  33.268093  34.322181  26.289175  41.348773
5   22.728172  30.228793  29.064081  37.663896  37.346794
6   30.774737  31.890813  25.561071  20.096018  28.260439
7   30.781745  36.151453  36.011899  28.063366  28.488486
8   24.757235  22.899910  21.468649  39.753877  27.451739
9   27.809628  23.736023  33.887452  21.930511  28.936299
10  25.522667  31.934512  27.445974  24.096839  29.859089
11  32.141659  30.332586  31.512359  26.828390  28.186294
12  26.637698  28.202234  25.934269  21.368587  30.887131
13  27.991095  21.849008  32.313911  25.463508  30.259727
14  33.645453  30.644915  35.697003  23.825871  32.011708
15  26.575950  25.646014  27.105752  28.442237  30.280827
16  24.174251  34.504132  32.328312  22.318782  37.441261
17  39.479446  35.893898  29.100376  24.646237  35.272259
18  27.984115  36.112225  31.041375  34.883195  31.781832
19  33.532866  30.052500  38.929352  30.634560  32.009947
20  39.415753  23.261205  23.647575  34.846984  24.134383
21  39.718106  27.931905  26.262726  39.614710  37.402574
22  39.337795  34.530223  25.693872  39.550325  28.659983
23  34.012282  34.736260  29.224950  33.070397  34.611033
24  31.882128  24.502996  31.491191  36.631929  26.527161
25  29.251827  27.824232  39.246319  33.361474  32.037309
26  26.150420  32.696246  26.628337  30.159153  26.820770
27  33.382166  32.882954  28.958506  31.980034  24.534692
28  22.543712  32.196959  30.833367  33.175157  41.915724
29  34.722397  25.435889  35.585081  23.420463  27.692077

In [5]:
s.max(), s.min()

(0    39.718106
 1    37.470395
 2    39.246319
 3    41.204466
 4    41.915724
 dtype: float64,
 0    17.235051
 1    21.849008
 2    21.468649
 3    20.096018
 4    24.134383
 dtype: float64)

Em seguida, geramos mais 10 amostras de tamanho 5, pois supomos que 1 motoboy faltou no serviço. Dessa forma, o tempo de entrega aumentou de 30 para 40 minutos:

In [6]:
mu, sigma = 40, 5 # # Média e desvio padrão (em minutos)
s2 = np.random.normal(mu, sigma, 50)
s2 = np. reshape(s2, (10, 5))
s2 =pd.DataFrame(s2)
s2

           0          1          2          3          4
0  39.658792  48.566714  36.276226  35.867807  39.507737
1  36.682609  45.633180  34.600342  34.262657  37.810900
2  37.509838  49.647660  44.747104  40.437756  33.872822
3  44.221815  34.998923  32.276145  45.940149  41.584713
4  44.604294  41.593638  44.284153  36.744872  34.828786
5  43.407973  35.982952  36.552251  37.722337  40.087396
6  38.230030  33.125244  36.781908  28.882984  43.126157
7  31.989712  34.478083  40.260825  36.302185  47.715073
8  33.535715  41.335254  39.803586  34.159533  42.616383
9  39.142268  43.858953  44.117521  50.816180  46.682640

In [7]:
s2.max(), s2.min()

(0    44.604294
 1    49.647660
 2    44.747104
 3    50.816180
 4    47.715073
 dtype: float64,
 0    31.989712
 1    33.125244
 2    32.276145
 3    28.882984
 4    33.872822
 dtype: float64)

In [8]:
# Une os dois datasets
restaurante= s.append(s2)

# Arrumando o dataset do restaurante
restaurante.index = range(len(restaurante))
restaurante = restaurante.rename(columns={0: 'x1', 1: 'x2', 2: 'x3', 3: 'x4', 4: 'x5'})

restaurante

           x1         x2         x3         x4         x5
0   38.820262  32.000786  34.893690  41.204466  39.337790
1   25.113611  34.750442  29.243214  29.483906  32.052993
2   30.720218  37.271368  33.805189  30.608375  32.219316
3   31.668372  37.470395  28.974209  31.565339  25.729521
4   17.235051  33.268093  34.322181  26.289175  41.348773
5   22.728172  30.228793  29.064081  37.663896  37.346794
6   30.774737  31.890813  25.561071  20.096018  28.260439
7   30.781745  36.151453  36.011899  28.063366  28.488486
8   24.757235  22.899910  21.468649  39.753877  27.451739
9   27.809628  23.736023  33.887452  21.930511  28.936299
10  25.522667  31.934512  27.445974  24.096839  29.859089
11  32.141659  30.332586  31.512359  26.828390  28.186294
12  26.637698  28.202234  25.934269  21.368587  30.887131
13  27.991095  21.849008  32.313911  25.463508  30.259727
14  33.645453  30.644915  35.697003  23.825871  32.011708
15  26.575950  25.646014  27.105752  28.442237  30.280827
16  24.174251  34.504132  32.328312  22.318782  37.441261
17  39.479446  35.893898  29.100376  24.646237  35.272259
18  27.984115  36.112225  31.041375  34.883195  31.781832
19  33.532866  30.052500  38.929352  30.634560  32.009947
20  39.415753  23.261205  23.647575  34.846984  24.134383
21  39.718106  27.931905  26.262726  39.614710  37.402574
22  39.337795  34.530223  25.693872  39.550325  28.659983
23  34.012282  34.736260  29.224950  33.070397  34.611033
24  31.882128  24.502996  31.491191  36.631929  26.527161
25  29.251827  27.824232  39.246319  33.361474  32.037309
26  26.150420  32.696246  26.628337  30.159153  26.820770
27  33.382166  32.882954  28.958506  31.980034  24.534692
28  22.543712  32.196959  30.833367  33.175157  41.915724
29  34.722397  25.435889  35.585081  23.420463  27.692077
30  39.658792  48.566714  36.276226  35.867807  39.507737
31  36.682609  45.633180  34.600342  34.262657  37.810900
32  37.509838  49.647660  44.747104  40.437756  33.872822
33  44.221815  34.998923  32.276145  45.940149  41.584713
34  44.604294  41.593638  44.284153  36.744872  34.828786
35  43.407973  35.982952  36.552251  37.722337  40.087396
36  38.230030  33.125244  36.781908  28.882984  43.126157
37  31.989712  34.478083  40.260825  36.302185  47.715073
38  33.535715  41.335254  39.803586  34.159533  42.616383
39  39.142268  43.858953  44.117521  50.816180  46.682640

# Criando as colunas $\bar{X}$ e R

In [9]:
restaurante['n_amostra'] = range(1, 41)

In [10]:
restaurante['xbarra'] = restaurante.mean(axis=1)

In [11]:
restaurante['R'] = restaurante.apply(amplitude, axis = 1)

In [12]:
restaurante

,x1,x2,x3,x4,x5,n_amostra,xbarra,R
0,38.820262,32.000786,34.893690,41.204466,39.337790,1,31.209499,40.204466
1,25.113611,34.750442,29.243214,29.483906,32.052993,2,25.440694,32.750442
2,30.720218,37.271368,33.805189,30.608375,32.219316,3,27.937411,34.271368
3,31.668372,37.470395,28.974209,31.565339,25.729521,4,26.567973,33.470395
4,17.235051,33.268093,34.322181,26.289175,41.348773,5,26.243879,36.348773
5,22.728172,30.228793,29.064081,37.663896,37.346794,6,27.171956,31.663896
6,30.774737,31.890813,25.561071,20.096018,28.260439,7,23.930513,24.890813
7,30.781745,36.151453,36.011899,28.063366,28.488486,8,27.916158,28.151453
8,24.757235,22.899910,21.468649,39.753877,27.451739,9,24.221902,30.753877
9,27.809628,23.736023,33.887452,21.930511,28.936299,10,24.383319,23.887452
10,25.522667,31.934512,27.445974,24.096839,29.859089,11,24.976514,20.934512
11,32.141659,30.332586,31.512359,26.828390,28.186294,12,26.833548,20.141659
12,26.637698,28.202234,25.934269,21.368587,30.887131,13,24.338320,17.887131
13,27.991095,21.849008,32.313911,25.463508,30.259727,14,25.312875,18.313911
14,33.645453,30.644915,35.697003,23.825871,32.011708,15,28.470825,20.697003
15,26.575950,25.646014,27.105752,28.442237,30.280827,16,25.675130,14.280827
16,24.174251,34.504132,32.328312,22.318782,37.441261,17,27.961123,20.441261
17,39.479446,35.893898,29.100376,24.646237,35.272259,18,30.398703,21.479446
18,27.984115,36.112225,31.041375,34.883195,31.781832,19,30.133790,17.112225
19,33.532866,30.052500,38.929352,30.634560,32.009947,20,30.859871,18.929352
20,39.415753,23.261205,23.647575,34.846984,24.134383,21,27.717650,18.415753
21,39.718106,27.931905,26.262726,39.614710,37.402574,22,32.155004,17.718106
22,39.337795,34.530223,25.693872,39.550325,28.659983,23,31.795366,16.550325
23,34.012282,34.736260,29.224950,33.070397,34.611033,24,31.609154,10.736260
24,31.882128,24.502996,31.491191,36.631929,26.527161,25,29.339234,12.128933
25,29.251827,27.824232,39.246319,33.361474,32.037309,26,31.286860,13.246319
26,26.150420,32.696246,26.628337,30.159153,26.820770,27,28.242487,6.545826
27,33.382166,32.882954,28.958506,31.980034,24.534692,28,29.956392,8.847474
28,22.543712,32.196959,30.833367,33.175157,41.915724,29,31.610820,19.372012
29,34.722397,25.435889,35.585081,23.420463,27.692077,30,29.475985,12.164618
30,39.658792,48.566714,36.276226,35.867807,39.507737,31,38.479546,17.566714
31,36.682609,45.633180,34.600342,34.262657,37.810900,32,36.831615,13.633180
32,37.509838,49.647660,44.747104,40.437756,33.872822,33,39.869197,16.647660
33,44.221815,34.998923,32.276145,45.940149,41.584713,34,38.836957,13.664004
34,44.604294,41.593638,44.284153,36.744872,34.828786,35,39.509291,9.775508
35,43.407973,35.982952,36.552251,37.722337,40.087396,36,38.292151,7.425021
36,38.230030,33.125244,36.781908,28.882984,43.126157,37,36.191054,14.243173
37,31.989712,34.478083,40.260825,36.302185,47.715073,38,38.124313,15.725361
38,33.535715,41.335254,39.803586,34.159533,42.616383,39,38.408412,9.080668
39,39.142268,43.858953,44.117521,50.816180,46.682640,40,44.102927,11.673911

In [13]:
# Gerando o arquivo .csv
restaurante.to_csv('dados_restaurantes.csv',index=False, decimal='.', sep= ";")

# Gráficos de controle $\bar{X}$ e R

# Gráficos da soma cumulativa